services:
  traefik:
    restart: "no"
    profiles:
      - donostart
    command: echo "Default GeoNature Traefik service disabled"

  redis:
    networks:
      - default

  postgres:
    ports:
      - "127.0.0.1:${POSTGRES_HOST_PORT}:5432"
    networks:
      - default
    volumes:
      # Add data directory to use with COPY FROM
      - ${GENTIANA_DATA_PATH}:/app/geonature/data/raw/

  taxhub:
    networks:
      - default
      - traefik
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.taxhub.entrypoints=web,websecure"
      - "traefik.http.routers.taxhub.middlewares=hardening@docker"
      - "traefik.http.routers.taxhub.tls.certresolver=myresolver"

  usershub:
    networks:
      - default
      - traefik
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.usershub.entrypoints=web,websecure"
      - "traefik.http.routers.usershub.middlewares=hardening@docker"
      - "traefik.http.routers.usershub.tls.certresolver=myresolver"

  geonature-backend:
    networks:
      - default
      - traefik
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.geonature-backend.entrypoints=web,websecure"
      - "traefik.http.routers.geonature-backend.middlewares=hardening@docker"
      - "traefik.http.routers.geonature-backend.tls.certresolver=myresolver"

  geonature-frontend:
    networks:
      - default
      - traefik
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.geonature.entrypoints=web,websecure"
      - "traefik.http.routers.geonature.middlewares=hardening@docker"
      - "traefik.http.routers.geonature.tls.certresolver=myresolver"

  geonature-install-db:
    networks:
      - default

  geonature-worker:
    networks:
      - default

networks:
  traefik:
    external: true