services:
  traefik:
    container_name: gentiana-local-traefik
    security_opt:
      - no-new-privileges:true
    networks:
      - default
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Static conf
      - ./config/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      # Dynamic static conf
      - ./config/traefik/config.yml:/etc/traefik/config.yml:ro
      # Certificats
      # Already done in docker-compose.yml
      #- ./data/traefik/certs:/etc/traefik/certs:ro
    labels:
      # Permettre à ce conteneur d'être accessible par traefik
      # Pour plus d'information, voir : https://docs.traefik.io/providers/docker/#exposedbydefault
      - "traefik.enable=true"
      # Utilise la configuration du routeur "traefik" définie dans le fichier de configuration #
      # dynamique : ./config/traefik/config.yml
      - "traefik.http.routers.traefik=true"

  redis:
    container_name: gentiana-local-redis
    networks:
      - default

  postgres:
    container_name: gentiana-local-postgres
    ports:
      - "127.0.0.1:${POSTGRES_HOST_PORT}:5432"
    networks:
      - default
    volumes:
      # Add data directory to use with COPY FROM
      - ${GEONATURE_DATA_IMPORT_ROOT_PATH}/geonature/data/raw/:/app/geonature/data/raw/

  taxhub:
    container_name: gentiana-local-taxhub
    networks:
      - default
      - traefik
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.taxhub.tls=true"
      - "traefik.http.routers.taxhub.tls.certResolver=default"


  usershub:
    container_name: gentiana-local-usershub
    networks:
      - default
      - traefik
    labels:
      - "traefik.docker.network=traefik"

  geonature-backend:
    container_name: gentiana-local-geonature-backend
    networks:
      - default
      - traefik
    labels:
      - "traefik.docker.network=traefik"

  geonature-frontend:
    container_name: gentiana-local-geonature-frontend
    networks:
      - default
      - traefik
    labels:
      - "traefik.docker.network=traefik"

  geonature-install-db:
    container_name: gentiana-local-geonature-install-db
    networks:
      - default

  geonature-worker:
    container_name: gentiana-local-geonature-worker
    networks:
      - default

networks:
  traefik:
    external: true
